/**
 * Tenant API client.
 * Each vendor's data lives behind their subdomain: {store}.api-matgary.test
 * This client builds the right URL based on the logged-in user's store_name.
 */
import { getStoredUser, getToken } from './auth';

const CENTRAL_API = process.env.NEXT_PUBLIC_API_URL || 'http://api-matgary.test/api';

/**
 * Builds the tenant base URL by replacing the central host with {store}.host.
 * Example:
 *   CENTRAL_API = http://api-matgary.test/api
 *   store_name  = nour
 *   result      = http://nour.api-matgary.test/api
 */
function getTenantApiBase(): string | null {
  const user = getStoredUser();
  if (!user || !user.store_name) return null;

  try {
    const u = new URL(CENTRAL_API);
    // Prepend the store name as a subdomain.
    u.hostname = `${user.store_name}.${u.hostname}`;
    // Tenant routes are mounted under /api/store/* by the backend
    return u.toString().replace(/\/$/, '') + '/store';
  } catch {
    return null;
  }
}

export interface ApiResponse<T = unknown> {
  status: boolean;
  message: string;
  data: T;
  errors?: Record<string, string[]>;
}

export async function tenantFetch<T = unknown>(
  endpoint: string,
  options: RequestInit = {}
): Promise<ApiResponse<T>> {
  const base = getTenantApiBase();
  if (!base) {
    return {
      status: false,
      message: 'No store associated with this account',
      data: null as T,
    };
  }

  const token = getToken();
  const isFormData = options.body instanceof FormData;

  const headers: Record<string, string> = {
    Accept: 'application/json',
    ...(isFormData ? {} : { 'Content-Type': 'application/json' }),
    ...(token ? { Authorization: `Bearer ${token}` } : {}),
    ...((options.headers as Record<string, string>) || {}),
  };

  try {
    const res = await fetch(`${base}${endpoint}`, {
      ...options,
      headers,
    });

    if (res.status === 204) {
      return { status: true, message: '', data: null as T };
    }

    return await res.json();
  } catch (err) {
    return {
      status: false,
      message: err instanceof Error ? err.message : 'Network error',
      data: null as T,
    };
  }
}

// ---------- Dashboard ----------
export interface DashboardOverview {
  stats: {
    total_sales: number;
    total_orders: number;
    total_products: number;
    total_customers: number;
    pending_orders: number;
    low_stock_count: number;
  };
  recent_orders: Array<{
    id: number;
    order_number: string;
    name: string;
    total: number;
    status: string;
    created_at: string;
  }>;
  top_products: Array<{
    id: number;
    name: string;
    image?: string;
    sold: number;
    revenue: number;
  }>;
  low_stock: Array<{
    id: number;
    name: string;
    stock: number;
  }>;
  sales_chart: Array<{
    date: string;
    total: number;
  }>;
}

export async function getDashboardOverview() {
  return tenantFetch<DashboardOverview>('/vendor/dashboard');
}

export async function getDashboardStats() {
  return tenantFetch<DashboardOverview['stats']>('/vendor/dashboard/stats');
}

// ---------- Products ----------
export interface Product {
  id: number;
  name: string;
  slug: string;
  description?: string;
  price: number;
  sale_price?: number | null;
  stock: number;
  status: boolean;
  image?: string | null;
  category?: { id: number; name: string } | null;
  brand?: { id: number; name: string } | null;
  created_at?: string;
}

export async function getProducts(params: { search?: string; page?: number } = {}) {
  const query = new URLSearchParams();
  if (params.search) query.set('search', params.search);
  if (params.page) query.set('page', String(params.page));
  const qs = query.toString();
  return tenantFetch<{ data: Product[]; meta?: { total: number; current_page: number; last_page: number } } | Product[]>(
    `/products${qs ? `?${qs}` : ''}`
  );
}

export async function deleteProduct(id: number) {
  return tenantFetch(`/products/${id}`, { method: 'DELETE' });
}

export async function createProduct(formData: FormData) {
  return tenantFetch<Product>('/products', { method: 'POST', body: formData });
}

export async function updateProduct(id: number, formData: FormData) {
  return tenantFetch<Product>(`/products/${id}`, { method: 'POST', body: formData });
}

export async function getProduct(id: number) {
  return tenantFetch<Product>(`/products/${id}`);
}

// ---------- Products Import/Export ----------
export interface ImportResult {
  imported: number;
  skipped: number;
  errors: string[];
}

export async function importProducts(file: File) {
  const fd = new FormData();
  fd.append('file', file);
  return tenantFetch<ImportResult>('/products/import', { method: 'POST', body: fd });
}

/**
 * Trigger a download of an .xlsx file generated by the backend.
 * Returns the blob URL the caller can open / use with an <a download>.
 */
export async function downloadProductsFile(kind: 'export' | 'template'): Promise<{ ok: boolean; blobUrl?: string; filename?: string; message?: string }> {
  const base = (() => {
    const u = getStoredUser();
    if (!u?.store_name) return null;
    try {
      const ur = new URL(process.env.NEXT_PUBLIC_API_URL || 'http://api-matgary.test/api');
      ur.hostname = `${u.store_name}.${ur.hostname}`;
      return ur.toString().replace(/\/$/, '') + '/store';
    } catch {
      return null;
    }
  })();

  if (!base) return { ok: false, message: 'No store associated' };

  const token = getToken();
  const endpoint = kind === 'export' ? '/products/export' : '/products/import-template';
  const filename = kind === 'export'
    ? `products-${new Date().toISOString().split('T')[0]}.xlsx`
    : 'products-template.xlsx';

  try {
    const res = await fetch(`${base}${endpoint}`, {
      headers: { ...(token ? { Authorization: `Bearer ${token}` } : {}) },
    });
    if (!res.ok) {
      const err = await res.json().catch(() => ({}));
      return { ok: false, message: err.message || `HTTP ${res.status}` };
    }
    const blob = await res.blob();
    return { ok: true, blobUrl: URL.createObjectURL(blob), filename };
  } catch (e) {
    return { ok: false, message: e instanceof Error ? e.message : 'Network error' };
  }
}

// ---------- Product Options & Variants ----------
export interface ProductOption {
  id: number;
  name: string;
  values?: Array<{ id: number; value: string }>;
}

export interface ProductVariant {
  id: number;
  sku?: string;
  price: number;
  quantity: number;
  status: boolean;
  options?: Record<string, string>;
}

export async function addProductOption(productId: number, payload: { name: string; values: string[] }) {
  return tenantFetch<ProductOption>(`/products/${productId}/options`, {
    method: 'POST',
    body: JSON.stringify(payload),
  });
}

export async function deleteProductOption(optionId: number) {
  return tenantFetch(`/product-options/${optionId}`, { method: 'DELETE' });
}

export async function addProductVariant(productId: number, payload: Record<string, unknown>) {
  return tenantFetch<ProductVariant>(`/products/${productId}/variants`, {
    method: 'POST',
    body: JSON.stringify(payload),
  });
}

export async function deleteProductVariant(variantId: number) {
  return tenantFetch(`/product-variants/${variantId}`, { method: 'DELETE' });
}

export async function getProductVariants(productId: number) {
  return tenantFetch<ProductVariant[]>(`/products/${productId}/variants`);
}

// ---------- Orders ----------
export type OrderStatus = 'pending' | 'processing' | 'shipped' | 'delivered' | 'cancelled';
export type PaymentStatus = 'pending' | 'paid' | 'failed' | 'refunded';

export interface OrderItem {
  id: number;
  product_id: number;
  product_variant_id?: number;
  product_name: string;
  variant_name?: string;
  price: number;
  quantity: number;
  total: number;
}

export interface Order {
  id: number;
  order_number: string;
  status: OrderStatus;
  payment_status: PaymentStatus;
  payment_method: string;
  subtotal: number;
  discount: number;
  shipping_cost: number;
  total: number;
  name: string;
  phone?: string;
  email?: string;
  address?: string;
  city?: string;
  notes?: string;
  items?: OrderItem[];
  invoice?: {
    download_url: string;
    preview_url: string;
    share_link_url: string;
  };
  created_at: string;
}

export async function getVendorOrders(params: { search?: string; status?: string; page?: number } = {}) {
  const query = new URLSearchParams();
  if (params.search) query.set('search', params.search);
  if (params.status && params.status !== 'all') query.set('status', params.status);
  if (params.page) query.set('page', String(params.page));
  const qs = query.toString();
  return tenantFetch<{ data: Order[]; meta?: { total: number; current_page: number; last_page: number } } | Order[]>(
    `/vendor/orders${qs ? `?${qs}` : ''}`
  );
}

export async function getOrder(id: number) {
  return tenantFetch<Order>(`/vendor/orders/${id}`);
}

export async function updateOrderStatus(id: number, status: OrderStatus) {
  return tenantFetch<Order>(`/vendor/orders/${id}/status`, {
    method: 'POST',
    body: JSON.stringify({ status }),
  });
}

export async function updateOrderPaymentStatus(id: number, payment_status: PaymentStatus) {
  return tenantFetch<Order>(`/vendor/orders/${id}/payment-status`, {
    method: 'POST',
    body: JSON.stringify({ payment_status }),
  });
}

export async function getInvoiceShareLink(id: number, locale = 'ar') {
  return tenantFetch<{ url: string; expires_in_days: number }>(
    `/orders/${id}/invoice/share-link?locale=${locale}`
  );
}

// ---------- Categories ----------
export interface Category {
  id: number;
  name: string;
  slug: string;
  image?: string | null;
  status?: boolean;
  created_at?: string;
}

export async function getCategories() {
  return tenantFetch<Category[]>('/categories');
}

export async function createCategory(formData: FormData) {
  return tenantFetch<Category>('/categories', { method: 'POST', body: formData });
}

export async function deleteCategory(id: number) {
  return tenantFetch(`/categories/${id}`, { method: 'DELETE' });
}

// ---------- SubCategories ----------
export interface SubCategory {
  id: number;
  name: string;
  slug: string;
  image?: string | null;
  status?: boolean;
  category?: { id: number; name: string };
  category_id?: number;
}

export async function getSubCategories() {
  return tenantFetch<SubCategory[]>('/sub-categories');
}

export async function createSubCategory(formData: FormData) {
  return tenantFetch<SubCategory>('/sub-categories', { method: 'POST', body: formData });
}

export async function deleteSubCategory(id: number) {
  return tenantFetch(`/sub-categories/${id}`, { method: 'DELETE' });
}

// ---------- Reviews ----------
export interface Review {
  id: number;
  rating: number;
  comment?: string;
  status: 'pending' | 'approved' | 'rejected';
  user?: { id: number; name: string };
  product?: { id: number; name: string; image?: string };
  created_at: string;
}

export async function getPendingReviews() {
  return tenantFetch<Review[]>('/vendor/reviews/pending');
}

export async function approveReview(id: number) {
  return tenantFetch(`/vendor/reviews/${id}/approve`, { method: 'POST' });
}

export async function rejectReview(id: number) {
  return tenantFetch(`/vendor/reviews/${id}/reject`, { method: 'POST' });
}

// ---------- Coupons ----------
export interface Coupon {
  id: number;
  code: string;
  type: 'fixed' | 'percentage';
  value: number;
  min_order_amount?: number | null;
  max_discount?: number | null;
  usage_limit?: number | null;
  used_count?: number;
  start_date: string;
  end_date: string;
  status: boolean;
}

export async function getCoupons() {
  return tenantFetch<Coupon[]>('/coupons');
}

export async function createCoupon(payload: Omit<Coupon, 'id' | 'used_count'>) {
  return tenantFetch<Coupon>('/coupons', {
    method: 'POST',
    body: JSON.stringify(payload),
  });
}

export async function deleteCoupon(id: number) {
  return tenantFetch(`/coupons/${id}`, { method: 'DELETE' });
}

// ---------- Brands ----------
export interface Brand {
  id: number;
  name: string;
  slug: string;
  image?: string | null;
  status?: boolean;
}

export async function getBrands() {
  return tenantFetch<Brand[]>('/brands');
}

export async function createBrand(formData: FormData) {
  return tenantFetch<Brand>('/brands', { method: 'POST', body: formData });
}

export async function deleteBrand(id: number) {
  return tenantFetch(`/brands/${id}`, { method: 'DELETE' });
}

// ---------- Contact Messages (Vendor inbox) ----------
export type ContactMessageStatus = 'unread' | 'read' | 'replied';

export interface ContactMessage {
  id: number;
  name: string;
  email?: string;
  phone?: string;
  subject?: string;
  message: string;
  status: ContactMessageStatus;
  created_at: string;
}

export async function getContactMessages() {
  return tenantFetch<ContactMessage[]>('/vendor/contact');
}

export async function getContactMessageUnreadCount() {
  return tenantFetch<{ count: number }>('/vendor/contact/unread-count');
}

export async function getContactMessage(id: number) {
  return tenantFetch<ContactMessage>(`/vendor/contact/${id}`);
}

export async function markContactMessageReplied(id: number) {
  return tenantFetch<ContactMessage>(`/vendor/contact/${id}/replied`, { method: 'POST' });
}

export async function deleteContactMessage(id: number) {
  return tenantFetch(`/vendor/contact/${id}`, { method: 'DELETE' });
}

// ---------- Sliders ----------
export interface Slider {
  id: number;
  title?: string;
  description?: string;
  image: string;
  link?: string | null;
  sort_order?: number;
  status: boolean;
}

export async function getSliders() {
  return tenantFetch<Slider[]>('/sliders/all');
}

export async function createSlider(formData: FormData) {
  return tenantFetch<Slider>('/sliders', { method: 'POST', body: formData });
}

export async function deleteSlider(id: number) {
  return tenantFetch(`/sliders/${id}`, { method: 'DELETE' });
}

// ---------- Pages ----------
export interface StorePage {
  id: number;
  title: string;
  slug: string;
  content?: string;
  status: boolean;
  created_at?: string;
}

export async function getStorePages() {
  return tenantFetch<StorePage[]>('/vendor/pages');
}

export async function createStorePage(payload: Record<string, unknown>) {
  return tenantFetch<StorePage>('/vendor/pages', {
    method: 'POST',
    body: JSON.stringify(payload),
  });
}

export async function deleteStorePage(id: number) {
  return tenantFetch(`/vendor/pages/${id}`, { method: 'DELETE' });
}

// ---------- Notifications ----------
export interface Notification {
  id: number;
  type: string;
  title: string;
  message: string;
  data?: Record<string, unknown>;
  is_read: boolean;
  read_at?: string | null;
  created_at: string;
}

export async function getNotifications() {
  return tenantFetch<Notification[]>('/notifications');
}

export async function getUnreadNotifications() {
  return tenantFetch<Notification[]>('/notifications/unread');
}

export async function getUnreadCount() {
  return tenantFetch<{ count: number }>('/notifications/unread-count');
}

export async function markNotificationRead(id: number) {
  return tenantFetch(`/notifications/${id}/read`, { method: 'POST' });
}

export async function markAllRead() {
  return tenantFetch('/notifications/mark-all-read', { method: 'POST' });
}

export async function deleteNotification(id: number) {
  return tenantFetch(`/notifications/${id}`, { method: 'DELETE' });
}

export async function clearAllNotifications() {
  return tenantFetch('/notifications/clear', { method: 'DELETE' });
}

// ---------- Settings ----------
export type SettingsMap = Record<string, string | null>;

export async function getSettings() {
  return tenantFetch<SettingsMap>('/settings');
}

export async function updateSettings(payload: SettingsMap) {
  return tenantFetch<SettingsMap>('/settings', {
    method: 'POST',
    body: JSON.stringify(payload),
  });
}

export async function updateLogo(file: File) {
  const fd = new FormData();
  fd.append('logo', file);
  return tenantFetch<{ logo: string }>('/settings/logo', { method: 'POST', body: fd });
}

// ---------- Subscription (central API, not tenant) ----------
export async function getMySubscription() {
  const token = getToken();
  const res = await fetch(`${CENTRAL_API}/subscription/current`, {
    headers: {
      Accept: 'application/json',
      ...(token ? { Authorization: `Bearer ${token}` } : {}),
    },
  });
  return res.json();
}

export async function getMySubscriptionHistory() {
  const token = getToken();
  const res = await fetch(`${CENTRAL_API}/subscription/history`, {
    headers: {
      Accept: 'application/json',
      ...(token ? { Authorization: `Bearer ${token}` } : {}),
    },
  });
  return res.json();
}

export async function cancelMySubscription() {
  const token = getToken();
  const res = await fetch(`${CENTRAL_API}/subscription/cancel`, {
    method: 'POST',
    headers: {
      Accept: 'application/json',
      ...(token ? { Authorization: `Bearer ${token}` } : {}),
    },
  });
  return res.json();
}

export async function getStoreUrl(): Promise<string | null> {
  const user = getStoredUser();
  if (!user || !user.store_name) return null;

  try {
    const u = new URL(CENTRAL_API);
    return `http://${user.store_name}.${u.hostname.replace(/^api\./, '')}`.replace('/api', '');
  } catch {
    return null;
  }
}
